# Generated by Django 3.0.8 on 2021-04-18 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200807_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='breed',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='gender',
            field=models.CharField(choices=[('G', 'No Category'), ('F', 'Female'), ('M', 'Male')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('G', 'No Category'), ('S', 'Shivajinagar'), ('K', 'Kothrud'), ('V', 'Viman nagar'), ('A', 'Aundh'), ('B', 'Baner'), ('P', 'Pashan'), ('K', 'Kondhwa'), ('H', 'Hadapsar'), ('I', 'Kharadi'), ('R', 'Vishrantwadi'), ('M', 'Bavdhan'), ('O', 'Bibvewadi'), ('D', 'Dhanori'), ('T', 'Katraj'), ('G', 'Wagholi'), ('Y', 'Yerwada'), ('W', 'Wanowrie'), ('N', 'Nanded')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('G', 'No Category'), ('D', 'Dogs'), ('C', 'Cats')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_bid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1, message='Number of days must be greater than 0.')]),
        ),
    ]
