# Generated by Django 3.0.8 on 2021-04-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210419_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
