# Generated by Django 3.0.8 on 2021-04-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_article_list_recommended_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommended_list',
        ),
    ]
